### ISSUE TITLE
Language Link Appearance (after click)

### ISSUE THREAD

**Issue by joeb-bsu** [BoiseStateCS401/CS401-activity-01-slap-fight-champs#1]
The background color of the links to HTML, CSS, and Javascript information turn bright white after being clicked and the font is no longer visible to the user.
---Update---
Looks like this is only an issue in my internet explorer browser.  Chrome & Edge don't have the issue.

**Comment by wesleygruenberg** [comment]
Added CSS colors to differentiate between link, visited and hover.
