### ISSUE TITLE
Frame Dynamic, but content not

### ISSUE THREAD

**Issue by joeb-bsu** [BoiseStateCS401/CS401-activity-01-slap-fight-champs#2]
The frame surrounding the hello world code is dynamic and will resize with the window, however, the text inside remains static and spills outside the frame.
-I'd like to know how to fix this as well.....

**Comment by wesleygruenberg** [comment]
Figured it out by reading up about the `<pre>` tag here: [Perfect pre tags](https://perishablepress.com/perfect-pre-tags/)

The `<code>` tag is redundant and meant for short single-line code snippets so I got rid of it.

Using the over-flow css setting, a scroll bar is put into the frame. There are more ways including resizing and wrapping, but I thought this way was effective enough for our assignment.
`pre {
	overflow: auto;
	width: 500px;
	}`
